# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    versioning-strategy: increase
    schedule:
      interval: "daily"
    reviewers:
      - "edgarrmondragon"
    ignore:
      - dependency-name: "singer-sdk"
    commit-message:
      prefix: "chore(deps): "
      prefix-development: "chore(deps-dev): "
  - package-ecosystem: pip
    directory: "/"
    versioning-strategy: increase
    schedule:
      interval: "daily"
    reviewers:
      - "edgarrmondragon"
    allow:
      - dependency-name: "singer-sdk"
    commit-message:
      prefix: "feat(deps): "
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
    reviewers:
      - "edgarrmondragon"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "edgarrmondragon"
